# Generated by Django 5.2.17 on 2026-08-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foundry", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                condition=models.Q(("domain", ""), _negated=True),
                fields=("organization", "domain"),
                name="unique_company_domain_per_org",
            ),
        ),
    ]
