# Generated by Django 5.2.17 on 2026-08-11 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foundry", "0002_company_unique_company_domain_per_org"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sync", "Source sync"),
                            ("analyze", "Entity analysis"),
                            ("enrich", "Entity enrichment"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("target_key", models.CharField(default="project", max_length=200)),
                ("progress_total", models.PositiveIntegerField(default=0)),
                ("progress_processed", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("request_budget", models.PositiveIntegerField(default=0)),
                ("requests_used", models.PositiveIntegerField(default=0)),
                ("rate_limit_remaining", models.PositiveIntegerField(blank=True, null=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foundry.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BatchJobItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(max_length=48)),
                ("entity_id", models.UUIDField()),
                ("status", models.CharField(default="queued", max_length=16)),
                ("output", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="foundry.batchjob",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foundry.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeadProject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100)),
                ("purpose", models.TextField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("languages", models.JSONField(default=list)),
                ("retention_days", models.PositiveIntegerField()),
                ("monthly_request_budget", models.PositiveIntegerField(default=1000)),
                ("allowed_domains", models.JSONField(blank=True, default=list)),
                ("network_execution_enabled", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foundry.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtractionProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("entity_type", models.CharField(max_length=48)),
                ("version", models.PositiveIntegerField(default=1)),
                ("field_rules", models.JSONField(default=dict)),
                ("reviewed_success_count", models.PositiveIntegerField(default=0)),
                ("reviewed_failure_count", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foundry.organization"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_profiles",
                        to="foundry.leadproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntityRelationship",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_type", models.CharField(max_length=48)),
                ("source_id", models.UUIDField()),
                ("target_type", models.CharField(max_length=48)),
                ("target_id", models.UUIDField()),
                ("relationship_type", models.CharField(max_length=64)),
                (
                    "confidence",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                ("status", models.CharField(default="candidate", max_length=24)),
                (
                    "evidence_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="foundry.sourcemessage"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foundry.organization"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to="foundry.leadproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrichmentResult",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_url", models.URLField(max_length=2048)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("content_sha256", models.CharField(blank=True, max_length=64)),
                ("candidate_data", models.JSONField(default=dict)),
                ("status", models.CharField(default="candidate", max_length=24)),
                ("extraction_profile_version", models.PositiveIntegerField(default=1)),
                (
                    "job_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment_results",
                        to="foundry.batchjobitem",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foundry.organization"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment_results",
                        to="foundry.leadproject",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contact_count", models.PositiveIntegerField(default=0)),
                ("inbound_count", models.PositiveIntegerField(default=0)),
                ("outbound_count", models.PositiveIntegerField(default=0)),
                ("first_contact_at", models.DateTimeField(blank=True, null=True)),
                ("last_contact_at", models.DateTimeField(blank=True, null=True)),
                (
                    "frequency_days",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("main_topics", models.JSONField(blank=True, default=list)),
                ("latest_outcome", models.CharField(blank=True, max_length=100)),
                ("sentiment", models.CharField(default="unknown", max_length=24)),
                (
                    "quality_score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("scoring_version", models.CharField(default="heuristic-v1", max_length=32)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="foundry.contact",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foundry.organization"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="foundry.leadproject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="batchjob",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="foundry.leadproject",
            ),
        ),
        migrations.CreateModel(
            name="LeadSource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("gmail", "Gmail"),
                            ("imap", "IMAP"),
                            ("pop3", "POP3"),
                            ("synthetic", "Synthetic fixture"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email_address", models.EmailField(blank=True, max_length=254)),
                ("host", models.CharField(blank=True, max_length=253)),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=320)),
                ("encrypted_password", models.TextField(blank=True)),
                ("use_tls", models.BooleanField(default=True)),
                ("rate_limit_per_minute", models.PositiveIntegerField(default=60)),
                ("max_messages_per_run", models.PositiveIntegerField(default=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("syncing", "Syncing"),
                            ("paused", "Paused"),
                            ("error", "Error"),
                            ("revoked", "Revoked"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("sync_cursor", models.CharField(blank=True, max_length=500)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=100)),
                (
                    "mailbox",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_source",
                        to="foundry.mailboxconnection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foundry.organization"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="foundry.leadproject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="batchjob",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="foundry.leadsource",
            ),
        ),
        migrations.CreateModel(
            name="ProjectEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(max_length=48)),
                ("entity_id", models.UUIDField()),
                ("review_status", models.CharField(default="candidate", max_length=24)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foundry.organization"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="foundry.leadproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(default="general", max_length=48)),
                ("color", models.CharField(default="#466653", max_length=7)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foundry.organization"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="foundry.leadproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntityTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(max_length=48)),
                ("entity_id", models.UUIDField()),
                (
                    "confidence",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                (
                    "evidence_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="foundry.sourcemessage",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foundry.organization"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="foundry.tag",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="batchjobitem",
            constraint=models.UniqueConstraint(
                fields=("job", "entity_type", "entity_id"), name="unique_job_entity"
            ),
        ),
        migrations.AddConstraint(
            model_name="leadproject",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="unique_project_slug_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="extractionprofile",
            constraint=models.UniqueConstraint(
                fields=("project", "entity_type", "version"), name="unique_extraction_profile"
            ),
        ),
        migrations.AddConstraint(
            model_name="entityrelationship",
            constraint=models.UniqueConstraint(
                fields=(
                    "project",
                    "source_type",
                    "source_id",
                    "target_type",
                    "target_id",
                    "relationship_type",
                ),
                name="unique_entity_relationship",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactmetric",
            constraint=models.UniqueConstraint(
                fields=("project", "contact"), name="unique_project_contact_metric"
            ),
        ),
        migrations.AddConstraint(
            model_name="leadsource",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_source_name_per_project"
            ),
        ),
        migrations.AddIndex(
            model_name="batchjob",
            index=models.Index(
                fields=["organization", "project", "created_at"],
                name="foundry_bat_organiz_51d0bf_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="batchjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["queued", "running"])),
                fields=("project", "kind", "target_key"),
                name="one_active_job_per_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectentity",
            constraint=models.UniqueConstraint(
                fields=("project", "entity_type", "entity_id"), name="unique_project_entity"
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("project", "category", "name"), name="unique_project_tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="entitytag",
            constraint=models.UniqueConstraint(
                fields=("tag", "entity_type", "entity_id"), name="unique_entity_tag"
            ),
        ),
    ]
