# Generated by Django 5.2.17 on 2026-08-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundry', '0003_batchjob_batchjobitem_leadproject_extractionprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productconcept',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productconcept',
            name='product_group',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
