# Generated by Django 5.2.17 on 2026-08-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundry', '0004_productconcept_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('encrypted_value', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
