# Generated by Django 5.2.17 on 2026-08-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundry', '0005_instancesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadproject',
            name='auto_digest_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
