# Generated by Django 5.2.17 on 2026-08-13 06:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundry', '0006_leadproject_auto_digest_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchjob',
            name='kind',
            field=models.CharField(choices=[('sync', 'Source sync'), ('analyze', 'Entity analysis'), ('enrich', 'Entity enrichment'), ('dedup', 'Contact deduplication')], max_length=16),
        ),
        migrations.CreateModel(
            name='MergeSuggestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=64)),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('duplicate_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_suggestions_as_duplicate', to='foundry.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundry.organization')),
                ('primary_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_suggestions_as_primary', to='foundry.contact')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'primary_contact', 'duplicate_contact'), name='unique_merge_suggestion_pair')],
            },
        ),
    ]
